### ISSUE TITLE
Feature: Add labels in Pull Request

### ISSUE THREAD

**Issue by w3teal** [nikhil-shuklaa/Cool-GitHub-Profile-README#16]
### Is your feature request related to a problem? Please describe.

I see some invalid pull request, but not responded.

### Describe the solution you'd like

I like to using label for communicating the user directly. Like "invalid", "profile", "tools", "articles", "tutorials", "documentation", ...

### Describe alternatives you've considered

Label is natural, so why not using it...

### Additional context

![Screenshot Capture - 2024-06-06 - 11-21-41](https://github.com/nikhil-shuklaa/Cool-GitHub-Profile-README/assets/143163098/bd8014a7-c576-4aec-a21f-5a07511ab853)

**Comment by nikhilsbuilds** [comment]
Yes sure, I'll do that. Thanks for bringing it to my attention!
